### PR TITLE
DRY circleci.yml jobs

### PR DESCRIPTION
**Pull request by simi**

### CODE REVIEW

**Comment by zzak** [comment]
Thanks @simi!

Would you mind pulling out `default-steps` to the top so a single job doesn't depend on sharing them? (In case we want to remove/rename it easily later).

**Comment by simi** [comment]
Sure, I can try. I wasn't sure how strict Circle CI is about format. Let me try.

**Comment by simi** [comment]
Original PR was merged, I'll submit my change to upstream later.

**Comment by zzak** [comment]
@simi Oh, thanks!

**Pull request closed without merging**
